version: "3.8"

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Adminer Service
  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080" # Access Adminer UI at http://localhost:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - app-network

  # ngrok Service to Expose the Database
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: always
    ports:
      - "4040:4040" # Access ngrok dashboard at http://localhost:4040
    depends_on:
      - db
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=adjusted-tarpon-engaging.ngrok-free.app"
      - "db:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
